name: qr_scanner_generator
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  path_provider: 0.4.1
  barcode_scan: 1.0.0
  qr_flutter: ^1.1.1
  image_gallery_saver: ^1.1.0
  permission_handler: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true



